# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  home24store-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: home24store-mysql
    volumes:
      - home24store-mysql-data:/var/lib/mysql
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=home24_store
      - MYSQL_DATABASE=home24_store_db
      - MYSQL_USER=home24_store
      - MYSQL_PASSWORD=home24_store

  # PHP (with nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: home24store-backend-app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8000"
    links:
      - mysql